<a href="https://colab.research.google.com/github/PayalBari1010/PayalBari1010/blob/main/Automated_Coding_Error_Detection_%26_Correction_Tool.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!tar --gunzip --extract --verbose --file=/content/Mini_Project_CodeNet.tar.gz

Streaming output truncated to the last 5000 lines.
data/p02400/C/s759115943.c
data/p02400/C/s712275927.c
data/p02400/C/s798579421.c
data/p02400/C/s528020509.c
data/p02400/C/s311608257.c
data/p02400/C/s338105596.c
data/p02400/C/s105361779.c
data/p02400/C/s436824455.c
data/p02400/C/s899545998.c
data/p02400/C/s057427567.c
data/p02400/C/s029918458.c
data/p02400/C/s801144710.c
data/p02400/C/s435890924.c
data/p02400/C/s732159372.c
data/p02400/C/s341007824.c
data/p02400/C/s889860929.c
data/p02400/C/s280059291.c
data/p02400/Python/
data/p02400/Python/s018814395.py
data/p02400/Python/s103710018.py
data/p02400/Python/s527003839.py
data/p02400/Python/s105869326.py
data/p02400/Python/s725908740.py
data/p02400/Python/s086243404.py
data/p02400/Python/s698753960.py
data/p02400/Python/s321755045.py
data/p02400/Python/s941277658.py
data/p02400/Python/s657439709.py
data/p02400/Python/s599996273.py
data/p02400/Python/s007048638.py
data/p02400/Python/s650342507.py
data/p02400/Python/s287182262.py
data/p02

In [ ]:
import pandas as pd

# Read the CSV file directly
csv_path = '/content/metadata/p04030.csv'
df = pd.read_csv(csv_path)

# Display the first few rows of the dataframe
print(df.head())


  submission_id problem_id     user_id        date language original_language  \
0    s646985956     p04030  u351221036  1601401164   Python    Python (3.8.2)   
1    s621197122     p04030  u317508154  1600152752   Python    Python (3.8.2)   
2    s701098815     p04030  u816631826  1599625641   Python    Python (3.8.2)   
3    s275588010     p04030  u607563136  1599516997   Python    Python (3.8.2)   
4    s351462698     p04030  u823885866  1599338676   Python    Python (3.8.2)   

  filename_ext    status  cpu_time   memory  code_size  accuracy  
0           py  Accepted      27.0   8948.0        366       NaN  
1           py  Accepted      29.0   8976.0        225       NaN  
2           py  Accepted      24.0   9092.0        124       NaN  
3           py  Accepted      28.0   9072.0        213       NaN  
4           py  Accepted     114.0  27000.0        565       NaN  


In [ ]:
import os
import pandas as pd

# Function to read code files from a directory
def load_code_files(directory_path):
    code_files = []
    for folder, _, files in os.walk(directory_path):
        for file_name in files:
            if file_name.endswith('.py') or file_name.endswith('.cpp') or file_name.endswith('.c'):
                file_path = os.path.join(folder, file_name)
                with open(file_path, 'r', encoding="utf-8") as file:
                    code = file.read()
                    code_files.append({'file_name': file_name, 'code': code})
    return pd.DataFrame(code_files)

# Load dataset (assuming data is in a 'data' folder within 'mini_project_codenet')
data_dir = '/content/data'
code_data = load_code_files(data_dir)

# Preview the first few code snippets
print(code_data.head())
print(code_data.tail())

      file_name                                               code
0  s792241522.c  #include <stdio.h>\nint main(void){\n    // Yo...
1  s793570395.c  #include<stdio.h>\nint main(void){\n  int  W,H...
2  s562970680.c  #include <stdio.h>\nint main(void){\n    long ...
3  s832645510.c  #include<stdio.h>\n\nint main(void) {\n\tunsig...
4  s623104488.c  #include<stdio.h>\n\nint main(void){\n  int W,...
           file_name                                               code
4795  s054953464.cpp  #include<stdio.h>\n#include<iostream>\nusing n...
4796  s386741267.cpp  #include <stdio.h>\nint main(void){\n\tint a,b...
4797  s179884447.cpp  #include<iostream>\n#include<vector>\n#include...
4798  s745499340.cpp  #include<iostream>\nusing namespace std;\n\nin...
4799  s150137933.cpp  #include<iostream>\n\nusing namespace std;\n\n...


In [ ]:
import os
import pandas as pd

# Function to load code files and associate them with metadata
def load_code_and_labels(data_directory, metadata_directory):
    code_data = []

    # Iterate through metadata files to get labels
    for metadata_file in os.listdir(metadata_directory):
        if metadata_file.endswith('.csv'):
            metadata_path = os.path.join(metadata_directory, metadata_file)
            metadata_df = pd.read_csv(metadata_path)

            # Extract problem ID from metadata filename
            problem_id = metadata_file.split('.')[0]
            problem_folder_path = os.path.join(data_directory, problem_id)

            if os.path.exists(problem_folder_path):
                # Combine submission_id and filename_ext to construct filenames
                metadata_df['filename'] = metadata_df['submission_id'].astype(str) + '.' + metadata_df['filename_ext']

                # Traverse language-based subfolders
                for language_folder in os.listdir(problem_folder_path):
                    lang_path = os.path.join(problem_folder_path, language_folder)
                    if os.path.isdir(lang_path):
                        # Process code files within the language folder
                        for code_file in os.listdir(lang_path):
                            if code_file in metadata_df['filename'].values:
                                file_path = os.path.join(lang_path, code_file)
                                with open(file_path, 'r', encoding='utf-8') as file:
                                    code = file.read()

                                # Find the status/label from metadata
                                status_row = metadata_df[metadata_df['filename'] == code_file]
                                if not status_row.empty:
                                    status = status_row['status'].values[0]
                                    code_data.append({'file_name': code_file, 'code': code, 'label': status})
                            else:
                                print(f"Code file {code_file} not found in metadata for problem ID {problem_id}.")

    return pd.DataFrame(code_data)

# Paths to data and metadata folders
data_directory = '/content/data'
metadata_directory = '/content/metadata'

# Load dataset
dataset = load_code_and_labels(data_directory, metadata_directory)

# Preview the dataset
print(dataset.head())


         file_name                                               code  \
0  s790850389.java  import java.io.*;\nimport java.util.*;\n\npubl...   
1  s038040107.java  import java.util.*;\n\npublic class Main {\n  ...   
2  s725232655.java  import java.util.*;\n\nclass Main{\n    public...   
3  s647572531.java  import java.util.Scanner;\n\npublic class Main...   
4  s312547212.java  import java.io.OutputStream;\nimport java.io.I...   

           label  
0       Accepted  
1  Runtime Error  
2       Accepted  
3       Accepted  
4       Accepted  


In [ ]:
# Map statuses to binary or categorical labels
def map_labels(status):
    if status == 'Accepted':
        return 'No Error'
    elif status in ['Runtime Error', 'Wrong Answer', 'WA: Presentation Error', 'Time Limit Exceeded', 'Compile Error', 'Memory Limit Exceeded']:
        return 'Error'
    else:
        return 'Unknown'

# Apply label mapping
dataset['mapped_label'] = dataset['label'].apply(map_labels)

# Display label distribution
print(dataset['mapped_label'].value_counts())


mapped_label
No Error    4673
Error       4150
Unknown        1
Name: count, dtype: int64


In [ ]:
dataset = dataset[dataset['mapped_label'] != 'Unknown']


Code Tokenization and Cleaning:

You may want to remove comments and unnecessary whitespace from the code files.

Use regular expressions (regex) to extract meaningful *content*

In [ ]:
import re
def clean_code(code):
    # Remove comments
    code = re.sub(r'//.*|/\*[\s\S]*?\*/', '', code)
    # Remove excess whitespace
    return re.sub(r'\s+', ' ', code).strip()

dataset['cleaned_code'] = dataset['code'].apply(clean_code)
dataset

file_name                                               code  \
0     s790850389.java  import java.io.*;\nimport java.util.*;\n\npubl...   
1     s038040107.java  import java.util.*;\n\npublic class Main {\n  ...   
2     s725232655.java  import java.util.*;\n\nclass Main{\n    public...   
3     s647572531.java  import java.util.Scanner;\n\npublic class Main...   
4     s312547212.java  import java.io.OutputStream;\nimport java.io.I...   
...               ...                                                ...   
8819    s034229201.go  package main\n\nimport (\n  "bufio"\n  "fmt"\n...   
8820    s170171201.go  package main\n\nimport (\n\t"fmt"\n\t"math"\n\...   
8821    s014353478.go  // https://atcoder.jp/contests/abc134/tasks/ab...   
8822    s758981016.go  package main\n\nimport (\n\t"bufio"\n\t"fmt"\n...   
8823    s148421020.go  package main\n\nimport (\n\t"bufio"\n\t"fmt"\n...   

                    label mapped_label  \
0                Accepted     No Error   
1           Runtime Error        Error   
2                Accepted     No Error   
3                Accepted     No Error   
4                Accepted     No Error   
...                   ...          ...   
8819  Time Limit Exceeded        Error   
8820             Accepted     No Error   
8821             Accepted     No Error   
8822             Accepted     No Error   
8823         Wrong Answer        Error   

                                           cleaned_code  
0     import java.io.*; import java.util.*; public c...  
1     import java.util.*; public class Main { public...  
2     import java.util.*; class Main{ public static ...  
3     import java.util.Scanner; public class Main { ...  
4     import java.io.OutputStream; import java.io.IO...  
...                                                 ...  
8819  package main import ( "bufio" "fmt" "os" "strc...  
8820  package main import ( "fmt" "math" "sort" ) va...  
8821  package main import ( "bufio" "bytes" "fmt" "o...  
8822  package main import ( "bufio" "fmt" "os" "sort...  
8823  package main import ( "bufio" "fmt" "math" "os...  

[8823 rows x 5 columns]

 Feature Extraction

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)  # Adjust max_features as needed
X = vectorizer.fit_transform(dataset['cleaned_code']).toarray()
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


 Split Data for Training and Testing

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, dataset['mapped_label'], test_size=0.2, random_state=42
)


Model Selection

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Predict and evaluate
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

       Error       0.65      0.62      0.63       841
    No Error       0.67      0.70      0.68       924

    accuracy                           0.66      1765
   macro avg       0.66      0.66      0.66      1765
weighted avg       0.66      0.66      0.66      1765



hyper parameter tuning

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.1, 1, 10]}
grid = GridSearchCV(LogisticRegression(max_iter=1000), param_grid, cv=5)
grid.fit(X_train, y_train)
print(grid.best_params_)


{'C': 10}


In [ ]:
import joblib
joblib.dump(model, 'code_error_classifier.pkl')


['code_error_classifier.pkl']

In [ ]:
import joblib
import re
from sklearn.feature_extraction.text import TfidfVectorizer

# Load the trained model and vectorizer
model = joblib.load('code_error_classifier.pkl')
vectorizer = TfidfVectorizer(max_features=5000)
vectorizer.fit(dataset['cleaned_code'])  # Refit to the original data

def clean_code(code):
    """Clean user input code."""
    code = re.sub(r'//.*|/\*[\s\S]*?\*/', '', code)  # Remove comments
    return re.sub(r'\s+', ' ', code).strip()          # Remove excess whitespace

def predict_code_error(user_code):
    """Predict if the input code has an error."""
    cleaned = clean_code(user_code)
    vectorized = vectorizer.transform([cleaned]).toarray()
    prediction = model.predict(vectorized)[0]
    return prediction


In [ ]:
!pip install gradio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.6/50.6 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.7/56.7 MB 11.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.8/319.8 kB 20.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.6/94.6 kB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.4/76.4 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.0/78.0 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 447.4/447.4 kB 24.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.5/144.5 kB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 74.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.2/73.2 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.7/63.7 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/1

In [ ]:
!pip install streamlit

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.9/41.9 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 59.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 65.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.3/79.3 kB 5.6 MB/s eta 0:00:00


In [ ]:
pip install openai==0.28

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.5/76.5 kB 2.2 MB/s eta 0:00:00


In [ ]:
pip install transformers autopep8 torch gradio


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 2.6 MB/s eta 0:00:00


In [ ]:
import gradio as gr
import autopep8
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

# Load GPT-Neo (Open Source Model from HuggingFace)
tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neo-1.3B")
model = AutoModelForCausalLM.from_pretrained("EleutherAI/gpt-neo-1.3B").to("cuda" if torch.cuda.is_available() else "cpu")

# Error explanations dictionary
error_explanations = {
    'SyntaxError': "There is a syntax issue. Make sure to use the correct symbols, colons, and indentation.",
    'NameError': "You're using a variable or function that hasn't been defined. Double-check your variable names.",
    'TypeError': "A function or operation is applied to an incompatible type. Check your data types.",
    'ZeroDivisionError': "The code tries to divide by zero. Add checks to avoid dividing by zero.",
    'IndentationError': "There is an indentation issue. Ensure consistent use of spaces or tabs.",
    'No Error': "Your code has no errors!"
}

def predict_code_error(user_code):
    """Detect if the input code has an error and return the error type."""
    try:
        exec(user_code)  # Try to execute the code
        return "No Error"
    except Exception as e:
        return type(e).__name__  # Return the error type

def get_error_explanation(error_type):
    """Provide detailed explanations for the detected error."""
    return error_explanations.get(error_type, "No specific explanation available.")

def auto_fix_code(user_code):
    """Automatically fix syntax and logical errors using autopep8 and GPT-Neo."""
    try:
        # Auto-fix basic syntax using autopep8
        syntax_fixed_code = autopep8.fix_code(user_code)

        # Use GPT-Neo for advanced code fixes (logic errors)
        input_text = f"Fix the following code:\n{syntax_fixed_code}"
        inputs = tokenizer(input_text, return_tensors="pt").to(model.device)
        outputs = model.generate(**inputs, max_new_tokens=150, temperature=0.5)

        fixed_code = tokenizer.decode(outputs[0], skip_special_tokens=True)
        return fixed_code.strip()

    except Exception as e:
        return f"Error during auto-fix: {str(e)}"

def detect_and_fix(user_code):
    """Detect errors, explain them, and attempt to fix the code."""
    error_type = predict_code_error(user_code)
    explanation = get_error_explanation(error_type)

    if error_type == "No Error":
        return f"Congrats! No errors detected.\n\nExplanation: {explanation}"
    else:
        fixed_code = auto_fix_code(user_code)
        return f"Error Type: {error_type}\nExplanation: {explanation}\n\nSuggested Fix:\n{fixed_code}"

# Gradio Interface with two tabs: Detect & Fix, and Manual Fix
with gr.Blocks() as app:
    gr.Markdown("# Code Error Detector & Auto-Fixer")

    with gr.Tabs():
        with gr.TabItem("Detect & Fix"):
            user_code = gr.Textbox(label="Enter your code snippet", lines=10, placeholder="Type your code here...")
            detect_button = gr.Button("Detect Error")
            result = gr.Textbox(label="Result", lines=10, interactive=False)

            def on_detect_click(code):
                return detect_and_fix(code)

            detect_button.click(on_detect_click, inputs=user_code, outputs=result)

        with gr.TabItem("Manual Fix"):
            manual_input = gr.Textbox(label="Enter your code snippet", lines=10, placeholder="Type your code here...")
            fix_button = gr.Button("Fix It!")
            fixed_result = gr.Textbox(label="Fixed Code", lines=10)

            def on_fix_click(code):
                return f"Your code:\n{code}\n\nTry fixing the error manually."

            fix_button.click(on_fix_click, inputs=manual_input, outputs=fixed_result)

# Launch the Gradio app
app.launch()


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/200 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.35k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/90.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


model.safetensors:   0%|          | 0.00/5.31G [00:00<?, ?B/s]

Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://8c2e322345f71b1578.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
